// Generated by scripts/download-ha-icons.mjs. Do not edit by hand.

package com.anadolstudio.ha_resources

object HaDomainFallbackIcons {
    val fallback: Map<String, String> = mapOf(
        "automation" to "mdi:robot",
        "calendar" to "mdi:calendar",
        "climate" to "mdi:thermostat",
        "light" to "mdi:lightbulb",
        "person" to "mdi:account",
        "scene" to "mdi:palette",
        "script" to "mdi:script-text",
        "sensor" to "mdi:eye",
        "switch" to "mdi:toggle-switch",
        "weather" to "mdi:weather-partly-cloudy",
        "zone" to "mdi:map-marker-radius",
    )

    fun resolve(domain: String): String? = fallback[domain]
}
