package com.anadolstudio.template.feature.manualSetupHomeAssistantUrl.presetnation

import com.anadolstudio.template.base.viewmodel.BaseController

interface ManualSetupHomeAssistantUrlController : BaseController
